export * from './asignaciones';
export * from './ceses';
export * from './configuracion';
export * from './empleados';
export * from './inicio';
export * from './inventario';
export * from './page.component';
export * from './reportes';
export * from './stock';
